language: go

go:
  - 1.10.x

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/smartystreets/goconvey
  - go get github.com/stretchr/testify/mock

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
