steps:
- name: gcr.io/cloud-builders/go
  args: [build, -o, acourse, -ldflags, -w -s, main.go]
  env:
  - PROJECT_ROOT=github.com/acoshift/acourse
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=0

- name: gcr.io/cloud-builders/yarn
  args: [install]
  id: yarn-install
  waitFor: ['-']
- name: gcr.io/cloud-builders/yarn
  args: [run, gulp]
  waitFor: [yarn-install]
  env:
  - NODE_ENV=production

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA, '.']

images:
- gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA
