routes:
  # app
  index: /
  signout: /signout
  profile: /profile
  profile.edit: /profile/edit
  course: /course/

  # auth
  auth.signin: /auth/signin
  auth.signin.password: /auth/signin/password
  auth.signin.check-email: /auth/signin/check-email
  auth.signin.link: /auth/signin/link
  auth.openid: /auth/openid
  auth.openid.google: /auth/openid?p=google.com
  auth.openid.github: /auth/openid?p=github.com
  auth.openid.callback: /auth/openid/callback
  auth.signup: /auth/signup
  auth.reset.password: /auth/reset/password

  # editor
  editor.course.create: /editor/course/create
  editor.course.edit: /editor/course/edit
  editor.content: /editor/content
  editor.content.create: /editor/content/create
  editor.content.edit: /editor/content/edit

  # admin
  admin.users: /admin/users
  admin.courses: /admin/courses
  admin.payments.pending: /admin/payments/pending
  admin.payments.history: /admin/payments/history
  admin.payments.reject: /admin/payments/reject
