routes:
  index: /

  # auth
  signin: /auth/signin
  signin.password: /auth/signin/password
  signin.check-email: /auth/signin/check-email
  signin.link: /auth/signin/link
  openid: /auth/openid
  openid.google: /auth/openid?p=google.com
  openid.github: /auth/openid?p=github.com
  openid.callback: /auth/openid/callback
  signup: /auth/signup

  # app
  signout: /signout
  reset.password: /auth/reset/password
  profile: /profile
  profile.edit: /profile/edit
  course: /course/

  # editor
  editor.course.create: /editor/course/create
  editor.course.edit: /editor/course/edit
  editor.content: /editor/content
  editor.content.create: /editor/content/create
  editor.content.edit: /editor/content/edit

  # admin
  admin.users: /admin/users
  admin.courses: /admin/courses
  admin.payments.pending: /admin/payments/pending
  admin.payments.history: /admin/payments/history
  admin.payments.reject: /admin/payments/reject
